# syntax=docker/dockerfile:1

# --- Build stage: compile and stage the server via Gradle's installDist -------
# Produces server/run/build/install/run/{bin,lib}: a self-contained launcher +
# every runtime jar, so the runtime image needs no build tooling.
FROM gradle:8-jdk17 AS build
WORKDIR /workspace

# Copy the whole repo (a .dockerignore keeps build/ and secrets out of context).
COPY . .

# --no-daemon: one-shot build in a container; --stacktrace aids CI debugging.
RUN ./gradlew --no-daemon --stacktrace :server:run:installDist

# --- Runtime stage: a container-aware JRE, non-root ---------------------------
FROM eclipse-temurin:17-jre-jammy AS runtime

# Container-aware heap sizing: honor the cgroup memory limit and take 75% of it.
ENV JAVA_TOOL_OPTIONS="-XX:MaxRAMPercentage=75 -XX:+UseContainerSupport"

# Run as an unprivileged, numeric UID (works with read-only rootfs / PodSecurity
# `runAsNonRoot`). A numeric USER lets Kubernetes verify non-root without a lookup.
RUN groupadd --gid 10001 lockers \
    && useradd --uid 10001 --gid 10001 --no-create-home --shell /usr/sbin/nologin lockers

WORKDIR /app
COPY --from=build /workspace/server/run/build/install/run/ /app/

USER 10001

# 8080 = public client/peer + probes + metrics; 8081 = internal admin (keep private).
EXPOSE 8080 8081

# The launcher generated by the `application` plugin (mainClass = MainKt).
ENTRYPOINT ["/app/bin/run"]
